configfile: "config/config.yaml"


def get_input_fastqs(wildcards):
    return config["samples"][wildcards.sample]

rule all:
    input:
        "results/bams/{sample}Aligned.Out.bam",

rule preprocess:
    input:
        get_input_fastqs
    output:
        "results/sf_reads/{sample}.s.sam"
    log:
        "logs/sort_filter/{sample}.log"
    threads: 20
    shell:
        "workflow/scripts/sort_filter.sh {config[cpus]} {wildcards.sample} {input} {output} {config[FORMAT]}"
