### Parameters you MUST set

# path to directory containing fastq files
samples:
  WT_1: data/fastq/WT_1
  WT_2: data/fastq/WT_2
  WT_ctl: data/fastq/WT_ctl
  KO_1: data/fastq/KO_1
  KO_2: data/fastq/KO_2
  KO_ctl: data/fastq/KO_ctl

# location of annotation gtf file
annotation: data/annotation/GRCh38.gtf

# -s4U control sample IDs
control_samples: ['WT_ctl', 'KO_ctl']

# location of genome fasta file
genome_fasta: data/genome/GRCh38.fa

# location of hisat2 indices (directory containing indices)
HISAT2: data/hisat2/grch38_tran/

# location of hisat3n indices (path to and common prefix of all .ht2 files)
HISAT_3N: data/hisat_3n/GRCh38

# location of STAR indices
STAR_index: data/star/

### Parameters you should probably double check

# If TRUE, hisat-3n will be used for alignment
use_hisat3n: False

# If TRUE STAR will be used for alignment;  if hisat-3n is also TRUE, hisat-3n will be used and not STAR
use_star: False

# If TRUE, index will be built for star and directory will be created at path set in STAR_index parameter
build_star: True

# If use_hisat3n TRUE, then this specifies path to hisat_3n executable
hisat3n_path: hisat-3n
  # If hisat-3n is on your PATH, this will just be hisat-3n

# Are you on Yale's HPC where hisat-3n can be loaded as a module using LMOD system?
Yale: True

# Format of reads
FORMAT: "PE" # (PE, SE, NU)
                    # [SE - single end reads]
                    # [NU - including non-unique] (not tested)


# Strandedness of reads
strandedness: "F" # (F, R); F means read 1 represents original RNA sequence (vs. its reverse complement).


# Type of browser tracks to generate
mut_tracks: "TC" # ("TC", "GA", "TC,GA")

# Add a 'chr' to each chromosome number during alignment. [Useful when aliner index is number-based, but GTF annotation is chr-based]
chr_tag: True

# Minimum base quality to call mutation
minqual: 40

# Which columns to keep in final cB.csv.gz file
keepcols: "sample,sj,io,ei,ai,GF,XF,rname"

# code specifying adapters to be trimmed that will be passed to cutadapt
adapter: "-a AGATCGGAAGAGC -A AGATCGGAAGAGC"

# Extra parameters to be passed to STAR
star_extra: "--outFilterMismatchNmax 20"

# Extra parameters to be passed to Hisat2
hisat2_extra: "--mp 1,0"

# Optional code to pass to cutadapt
cutadapt_extra: "--minimum-length 20"

# String common to spike-in gene_ids in annotation gtf
  # If you have no spike-ins, then this should be "\"\"", i.e., an empty string ("")
spikename: "\"\""

# If True, tracks will be normalized
normalize: True

# Are you using the Windows subsystem for linux? 0 = Yes, 1 = No
WSL: 1
